[package]
name = "ratbagtui"
version = "0.1.0"
edition = "2026"

[dependencies]
crossterm = "0.29.0"
evdev = "0.13.2"
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["full"] }
zbus = { version = "5.13.2", features = ["tokio"] }
